[workspace]
authors = ["chrisdewa <christian.delaflor@gmail.com>"]
channels = ["conda-forge"]
name = "Método"
platforms = ["linux-64", "win-64"]
version = "0.1.6"

[tasks]
build = "quarto render --execute"
preview = "quarto preview"

[dependencies]
quarto = ">=1.9.38,<2"
python = "3.14.*"
jupyter = ">=1.1.1,<2"
ipykernel = ">=7.3.0,<8"
numpy = ">=2.5.3,<3"
pandas = ">=3.0.5,<4"
matplotlib = ">=3.11.1,<4"
scipy = ">=1.18.0,<2"
statsmodels = ">=0.15.0,<0.16"
scikit-learn = ">=1.9.0,<2"
seaborn = ">=0.13.2,<0.14"
